fuel_dine/base/utils/urls.py
# -*- coding: utf-8 -*-

# Third Party Stuff
import django_sites as sites
from django.core.urlresolvers import reverse as django_reverse

URL_TEMPLATE = '{scheme}://{domain}/{path}'


def build_url(path, scheme='http', domain='localhost'):
    return URL_TEMPLATE.format(scheme=scheme, domain=domain, path=path.lstrip('/'))


def is_absolute_url(path):
    """Test wether or not `path` is absolute url.
    """
    return path.startswith('http')


def get_absolute_url(path):
    """Return a path as an absolute url.
    """
    if is_absolute_url(path):
        return path
    site = sites.get_current()
    return build_url(path, scheme=site.scheme, domain=site.domain)


def reverse(viewname, *args, **kwargs):
    """Same behavior as django's reverse but uses django_sites to compute absolute url.
    """
    return get_absolute_url(django_reverse(viewname, *args, **kwargs))

fuel_dine/restaurants/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [

    # APIs exposed

    url(r'^api/restaurant/$', views.RestaurantView.as_view(),
        name='restaurant-create-list'),

    url(r'^api/restaurant/(?P<pk>\d+)/$',
        views.RestaurantDetailView.as_view(),
        name='restaurant-detail'),

    url(r'^api/restaurant/(?P<pk>\d+)/review/$', views.ReviewView.as_view(),
        name='review-create'),

    url(r'^api/review/(?P<pk>\d+)/comment/$', views.CommentView.as_view(),
        name='comment-create'),

    url(r'^api/restaurant/(?P<pk>\d+)/vote/(?P<action>\w+)/$',
        views.vote_for_restaurant,
        name='restaurant-vote'),

    url(r'^api/restaurant/(?P<pk>\d+)/thumbdown/$',
        views.thumbs_down_for_restaurant,
        name='restaurant-thumbdown'),

    url(r'^api/restaurant/(?P<pk>\d+)/visited/$',
        views.mark_restaurant_visited,
        name='restaurant-visited'),

    url(r'^api/me/$', views.who_am_i,
        name='who-am-i'),

    # This API would take much time, so dropping this extra feature for now.
    # url(r'^api/votes/reset/$', views.reset_vote_count_for_restaurants,
    #     name='reset-vote-count'),

    url(r'^api/results/$', views.select_restaurant_for_dining_based_on_votes,
        name='choose-restaurant-for-dining'),

    # Normal Django Templates url go below

    url(r'^add_restaurant_geocoding/$',
        views.RestaurantGeocodingTemplate.as_view(),
        name='restaurant-add-geo'),

    url(r'^add_restaurant_reverse_geocoding/$',
        views.RestaurantReverseGeocodingTemplate.as_view(),
        name='restaurant-add-geo-rev'),

    url(r'^$', TemplateView.as_view(template_name='restaurants/index.html'),
        name='home'),

    url(r'^restaurant/(?P<pk>\d+)/$',
        TemplateView.as_view(template_name='restaurants/restaurant_detail.html'),
        name='restaurant-detail-template'),

    url(r'^restaurant/(?P<pk>\d+)/review/$',
        TemplateView.as_view(template_name='restaurants/add_review_form.html'),
        name='review-add-template'),

    url(r'^review/(?P<pk>\d+)/comment/$',
        TemplateView.as_view(template_name='restaurants/add_comment_form.html'),
        name='comment-add-template'),

]

fuel_dine/urls.py
# -*- coding: utf-8 -*-
"""Root url routering file.

You should put the url config in their respective app putting only a
refernce to them here.
"""

# Third Party Stuff
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from rest_framework.authtoken import views

# fuel_dine Stuff
from fuel_dine.base import views as base_views

from . import routers, schemas

from fuel_dine.restaurants import urls as restaurant_urls

handler500 = base_views.server_error

# Top Level Pages
# ==============================================================================
urlpatterns = [
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/'},  name='logout'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # Your stuff: custom urls go here
    url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^', include(restaurant_urls.urlpatterns)),
    # REST API Docs
    # url(r'^docs/', include_docs_urls(title='Fuel Dine API'))
    url(r'^docs/', include('rest_framework_docs.urls')),
]

urlpatterns += [

    url(r'^(?P<filename>(robots.txt)|(humans.txt))$',
        base_views.root_txt_files, name='root-txt-files'),

    # Rest API
    url(r'^api/', include(routers.router.urls)),

    # Django Admin
    url(r'^{}/'.format(settings.DJANGO_ADMIN_URL), admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.API_DEBUG:
    urlpatterns += [
        # Browsable API
        url('^schema/$', schemas.schema_view, name='schema'),
        url(r'^api-playground/$', schemas.swagger_schema_view, name='api-playground'),
        url(r'^api/auth-n/', include('rest_framework.urls', namespace='rest_framework')),
    ]

if settings.DEBUG:
    from django.views import defaults as dj_default_views
    from django.urls import get_callable

    # debug toolbar
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

    # Livereloading
    urlpatterns += [url(r'^devrecargar/', include('devrecargar.urls', namespace='devrecargar'))]

    urlpatterns += [
        url(r'^400/$', dj_default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', dj_default_views.permission_denied, kwargs={'exception': Exception('Permission Denied!')}),
        url(r'^403_csrf/$', get_callable(settings.CSRF_FAILURE_VIEW)),
        url(r'^404/$', dj_default_views.page_not_found, kwargs={'exception': Exception('Not Found!')}),
        url(r'^500/$', handler500),
    ]

fuel_dine/base/models.py
# -*- coding: utf-8 -*-

# Standard Library
import uuid

# Third Party Stuff
from django.db import models
from uuid_upload_path import upload_to
from versatileimagefield.fields import PPOIField, VersatileImageField


class UUIDModel(models.Model):
    """ An abstract base class model that makes primary key `id` as UUID
    instead of default auto incremented number.
    """
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)

    class Meta:
        abstract = True


class TimeStampedUUIDModel(UUIDModel):
    """An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields with UUID as primary_key field.
    """
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True


class ImageMixin(models.Model):
    """An abstract base class model that provides a VersatileImageField Image with POI
    """

    image = VersatileImageField(upload_to=upload_to, blank=True, null=True, ppoi_field='image_poi',
                                verbose_name="image")
    image_poi = PPOIField(verbose_name="image's Point of Interest")  # point of interest

    class Meta:
        abstract = True

fuel_dine/restaurants/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _

# Third party imports
from vote.models import VoteModel

# Local imports of fuel_dine
from fuel_dine.users.models import Profile

# Create your models here.


class Place(models.Model):
    lat = models.FloatField(verbose_name=_(u'latitude'))
    lon = models.FloatField(verbose_name=_(u'longitude'))

    def __str__(self):
        return "Coordinates: {}, {}".format(self.lat, self.lon)

    class Meta:
        abstract = True
        verbose_name = "place"
        verbose_name_plural = "places"


class ReviewComments(models.Model):
    user = models.ForeignKey(Profile, null=False,
                             blank=False, verbose_name=_(u'user'))
    text = models.TextField(null=True, blank=True, verbose_name=_(u'text'))
    posted_at = models.DateTimeField(default=timezone.now, null=False,
                                     blank=False, verbose_name=_(u'posted_at'))

    class Meta:
        abstract = True
        verbose_name = "restaurant"
        verbose_name_plural = "restaurants"


class Restaurant(VoteModel, Place):
    name = models.CharField(max_length=100, verbose_name=_(u'name'))
    is_active = models.BooleanField(default=True, verbose_name=_(u'is_active'))
    description = models.TextField(blank=True, null=True,
                                   verbose_name=_(u'description'))
    website = models.URLField(blank=True, null=True, verbose_name=_(u'website'))
    address = models.TextField(verbose_name='Address',
                               help_text='Location of the restaurant')
    contact = models.CharField(max_length=10, blank=True, null=True,
                               verbose_name=_(u'contact'))
    created_at = models.DateTimeField(default=timezone.now, null=False,
                                      blank=False, verbose_name=_(u'created_at'))

    class Meta:
        verbose_name = "restaurant"
        verbose_name_plural = "restaurants"
        ordering = ['-created_at']

    def __str__(self):
        return "{0}".format(self.name)

    def get_votes_count(self):
        return self.votes.count()


class Visit(models.Model):
    user = models.ForeignKey(Profile, null=False,
                             on_delete=models.CASCADE,
                             blank=False, verbose_name=_(u'user'))
    restaurant = models.ForeignKey(Restaurant, null=False, blank=False,
                                   on_delete=models.CASCADE,
                                   verbose_name=_(u'restaurant'))
    created_at = models.DateTimeField(default=timezone.now, null=False,
                                      blank=False, verbose_name=_(u'created_at'))

    def __str__(self):
        return "{} - {}".format(self.user, self.restaurant)

    class Meta:
        ordering = ['-created_at']
        verbose_name = "visit"
        verbose_name_plural = "visits"


class Review(ReviewComments):
    restaurant = models.ForeignKey(Restaurant, null=False, blank=False,
                                   verbose_name=_(u'restaurant'),
                                   related_name='reviews',
                                   on_delete=models.CASCADE)

    class Meta:
        verbose_name = "review"
        verbose_name_plural = "reviews"
        ordering = ['-posted_at']

    def __str__(self):
        return "{0} - {1}".format(self.user, self.text)


class Comment(ReviewComments):
    review = models.ForeignKey(Review, null=False, blank=False,
                               verbose_name=_(u'review'),
                               related_name='comments',
                               on_delete=models.CASCADE)

    class Meta:
        verbose_name = "comment"
        verbose_name_plural = "comments"
        ordering = ['-posted_at']

    def __str__(self):
        return "{0} - {1}".format(self.user, self.text)


class ThumbDown(models.Model):
    user = models.ForeignKey(Profile, null=False,
                             blank=False, verbose_name=_(u'user'))
    restaurant = models.ForeignKey(Restaurant, null=False, blank=False,
                                   verbose_name=_(u'restaurant'))
    created_at = models.DateTimeField(default=timezone.now, null=False,
                                      blank=False, verbose_name=_(u'created_at'))

    class Meta:
        ordering = ['-created_at']
        verbose_name = "thumb_down"
        verbose_name_plural = "thumb_downs"

    def __str__(self):
        return "{0} did thumbs down to {1}".format(self.user, self.restaurant)

fuel_dine/users/models.py
# -*- coding: utf-8 -*-

# Third Party Stuff
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from rest_framework.authtoken.models import Token

# fuel_dine Stuff
from fuel_dine.base.models import UUIDModel


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        """Creates and saves a User with the given email and password.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)


@python_2_unicode_compatible
class User(AbstractBaseUser, UUIDModel, PermissionsMixin):
    first_name = models.CharField(_('First Name'), max_length=120, blank=True)
    last_name = models.CharField(_('Last Name'), max_length=120, blank=True)
    email = models.EmailField(_('email address'), unique=True, db_index=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text='Designates whether the user can log into this admin site.')

    is_active = models.BooleanField('active', default=True,
                                    help_text='Designates whether this user should be treated as '
                                              'active. Unselect this instead of deleting accounts.')
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    USERNAME_FIELD = 'email'
    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ('-date_joined', )

    def __str__(self):
        return str(self.email)

    def get_full_name(self):
        """Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '{} {}'.format(self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Returns the short name for the user.
        """
        return self.first_name.strip()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.user.email)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

fuel_dine/base/views.py
# -*- coding: utf-8 -*-

# Standard Library
import sys

# Third Party Stuff
from django import http
from django.conf import settings
from django.shortcuts import render
from django.views.defaults import server_error as default_server_error


def server_error(request, *args, **kwargs):
    """JSON aware server 500 error response.

    As we don't want to return html response for a json request.
    """
    if not settings.DEBUG and request.META.get('CONTENT_TYPE', None) == 'application/json':
        exc_type, exc_obj, exc_tb = sys.exc_info()
        response_dict = {
            'error_type': exc_type.__name__ if exc_type else 'ServerError',
            'errors': [{'message': 'Server application error', }]
        }
        return http.JsonResponse(data=response_dict, status=500)

    return default_server_error(request, *args, **kwargs)


def csrf_failure(request, reason='', template_name='403_csrf.html'):
    """ Custom view used when request fails CSRF protection.

    Custom view is used because Django compressor complains if trying to
    use the in-built default view due to use `render` function. It keeps the
    logic but make things less magical.
    """
    from django.middleware.csrf import REASON_NO_REFERER, REASON_NO_CSRF_COOKIE
    ctx = {
        'reason': reason,
        'no_referer': reason == REASON_NO_REFERER,
        'no_cookie': reason == REASON_NO_CSRF_COOKIE,
        'DEBUG': settings.DEBUG,
    }
    return render(request, template_name=template_name, context=ctx, status=403)


def root_txt_files(request, filename):
    return render(request, filename, {}, content_type='text/plain')

fuel_dine/templates/restaurants/add_comment_form.html
{% extends 'pages/base.html' %}
{% load i18n %}
{% load static %}
{% load rest_framework %}
{% block title %}{% trans 'Home' %} • {{ block.super }}{% endblock title %}
{% block body_classes %}{{ block.super}} page-home {% endblock body_classes %}
{% block content %}
{% load material_form %}
{% block comment_form %}
  <p>Write a new comment:</p>
  <form id="add-comment">
    {% csrf_token %}
      <div class="input-field col s12">
        <textarea id="id_comment_text"
                  placeholder="I think that this review..."
                  class="materialize-textarea" required></textarea>
        <label for="id_comment_text">Comment</label>
      </div>
      <input type="hidden" id="review_id" name="restaurant_id" value="{{ pk }}">
      <input type="hidden" id="user_id" name="user_id" value="{{ request.user.profile.id }}">
    <input class="waves-effect waves-light btn" type="submit" value="Submit" />
    <div id="submit-result"></div>
  </form>
{% endblock %}
{% endblock content %}

fuel_dine/templates/restaurants/add_restaurant_base.html
{% extends 'pages/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'Add Restaurant' %} • {{ block.super }}{% endblock title %}
{% block body_classes %}{{ block.super}} page-home {% endblock body_classes %}

{% block css %}
  {{ block.super }}
  <link href="{% static 'css/google_services/geocoding.css' %}"
        rel="stylesheet">
{% endblock %}

{% block content %}
  <h4>Add a new Restaurant</h4>
  <div id="map"></div>
{% endblock %}

{% block add_restaurant_form %}
  <div class="row">
      <form class="col s12" method="post" action="{% url 'restaurant-create-list' %}"
            id="add-restaurant">
        {% csrf_token %}
        <div class="input-field col s12">
          <input placeholder="Sagar Ratna" id="id_name" type="text"
                 class="validate" required>
          <label for="id_name">Name</label>
        </div>
        <div class="input-field col s12">
          <input id="id_lat" type="number" step="any"
                 class="validate" required>
          <label for="id_lat">Latitude</label>
        </div>
        <div class="input-field col s12">
          <input id="id_lon" type="number" step="any"
                 class="validate" required>
          <label for="id_lon">Longitude</label>
        </div>
        <div class="input-field col s12">
          <textarea id="id_description"
                    placeholder="Really good restaurant in South Delhi"
                    class="materialize-textarea"></textarea>
          <label for="id_description">Description</label>
        </div>
        <div class="input-field col s12">
          <textarea id="id_address"
                    placeholder="South Delhi"
                    class="materialize-textarea" required></textarea>
          <label for="id_address">Address</label>
        </div>
        <div class="input-field col s12">
          <input id="id_website" type="text"
                 class="validate">
          <label for="id_website">Website</label>
        </div>
        <div class="input-field col s12">
          <input id="id_contact" type="number" maxlength="10"
                 class="validate" required>
          <label for="id_contact">Contact No</label>
        </div>
        <input class="waves-effect waves-light btn" type="submit"
           value="Submit" />
        <div id="submit-result"></div>
      </form>
    </div>
{% endblock %}
{% block js %}
  {{ block.super }}
  <script src="{% static 'js/google_services/' %}{{ js_file_name }}"></script>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_SERVICES_API_KEY }}&callback=initMap">
  </script>
{% endblock %}

fuel_dine/templates/restaurants/add_restaurant_geocoding.html
{% extends 'restaurants/add_restaurant_base.html' %}
{% load static %}
{% load rest_framework %}
{% load material_form %}
{% block content %}
  {{ block.super }}
  <p>Geocode restaurant location and fill in the form below to add it to the
  app.</p>
  <div class="add-restaurant">
    <div id="floating-panel">
      <input id="address" type="textbox" value="Sydney, NSW">
      <input id="submit" type="button" value="Geocode">
    </div>
  </div>
  {% block add_restaurant_form %}
    {{ block.super }}
  {% endblock %}
{% endblock content %}

fuel_dine/templates/restaurants/add_restaurant_geocoding_reverse.html
{% extends 'restaurants/add_restaurant_base.html' %}
{% load static %}
{% load rest_framework %}
{% load material_form %}
{% block content %}
  {{ block.super }}
  <p>Reverse geocode restaurant location and fill in the form below to add
    it to the app.</p>
  <div class="add-restaurant">
    <div id="floating-panel">
      <input id="latlng" type="text" value="40.714224,-73.961452">
      <input id="submit" type="button" value="Reverse Geocode">
    </div>
  </div>
  {% block add_restaurant_form %}
    {{ block.super }}
  {% endblock %}
{% endblock content %}

fuel_dine/templates/restaurants/add_review_form.html
{% extends 'pages/base.html' %}
{% load i18n %}
{% load static %}
{% load rest_framework %}
{% block title %}{% trans 'Home' %} • {{ block.super }}{% endblock title %}
{% block body_classes %}{{ block.super}} page-home {% endblock body_classes %}
{% load material_form %}
{% block content %}
  {% block review_form %}
    <p>Write a new review:</p>
    <form id="add-review">
      {% csrf_token %}
      <div class="input-field col s12">
        <textarea id="id_review_text"
                  placeholder="This is awesome restaurant!"
                  class="materialize-textarea" required></textarea>
        <input type="hidden" id="restaurant_id" name="restaurant_id" value="{{ pk }}">
        <input type="hidden" id="user_id" name="user_id" value="{{ request.user.profile.id }}">
        <label for="id_review_text">Review</label>
      </div>
      <input class="waves-effect waves-light btn" type="submit"
             value="Submit" />
      <div id="submit-result"></div>
    </form>
  {% endblock %}
{% endblock content %}

fuel_dine/templates/restaurants/index.html
{% extends 'pages/base.html' %}
{% load i18n %}
{% load static %}
{% load rest_framework %}
{% block title %}{% trans 'Home' %} • {{ block.super }}{% endblock title %}
{% block body_classes %}{{ block.super}} page-home {% endblock body_classes %}
{% block onloadfunction %}
  populateRestaurantList();
{% endblock onloadfunction %}
{% block content %}
  <p>
    {% trans 'Welcome to Fuel Dine restaurants page' %}
    {% if request.user.is_authenticated %}
      <b>{{ request.user }}</b>
    {% endif %}
  </p>
  <p>You can add a new restaurant by <a href="{% url 'restaurant-add-geo' %}">geocoding</a> or
    <a href="{% url 'restaurant-add-geo-rev' %}">reverse geocoding</a> to the app.
  </p>
  <button data-target="modal1" class="btn" id="vote-count-res">Get top
    restaurant for dining</button>
  {# Disabling the extra feature #}
{#  <a class="waves-effect waves-green btn" id="reset-vote-count">Click here to reset vote count</a>#}
{#  <div id="reset-count-res"></div>#}
  <p>Here is the list of restaurants:</p>
  <div id="restaurant-list">There are no restaurants to display.</div>
  <div id="restaurant-dine-result">
    <!-- Modal Structure -->
    <div id="modal1" class="modal">
      <div class="modal-content">
        <h4>Top Restaurants for dining:</h4>
        <div id="modal-content-res"></div>
      </div>
      <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect
        waves-green btn-flat">Close</a>
      </div>
    </div>
  </div>
{% endblock content %}

fuel_dine/templates/restaurants/restaurant_detail.html
{% extends 'pages/base.html' %}
{% load i18n %}
{% load static %}
{% load rest_framework %}
{% block title %}{% trans 'Home' %} • {{ block.super }}{% endblock title %}
{% block body_classes %}{{ block.super}} page-home {% endblock body_classes %}
{% block onloadfunction %}
  populateRestaurantDetail({{ pk }});
  get_my_email();
{% endblock onloadfunction %}
{% block content %}
  <p>
    {% trans 'Welcome to Fuel Dine restaurants page' %}
    {% if request.user.is_authenticated %}
      <b>{{ request.user }}</b>
    {% endif %}
  </p>
  <div id="restaurant-detail-view">
  </div>
{% endblock content %}